# Generated by Django 5.2 on 2025-04-21 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPhong',
            fields=[
                ('ma_day_phong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_day_phong', models.CharField(max_length=50)),
                ('so_phong', models.IntegerField()),
                ('doi_tuong', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('ma_loai_phong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_loai_phong', models.CharField(max_length=50)),
                ('so_luong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('mssv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=50)),
                ('cccd', models.CharField(max_length=12)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.BooleanField()),
                ('que_quan', models.CharField(max_length=100)),
                ('trang_thai', models.CharField(max_length=20)),
                ('so_phong', models.CharField(max_length=20)),
                ('so_giuong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaiSan',
            fields=[
                ('ma_tai_san', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_tai_san', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('ma_phong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('so_luong_sv', models.IntegerField()),
                ('gia', models.IntegerField()),
                ('danh_sach_sv', models.TextField(blank=True, null=True)),
                ('trang_thai', models.CharField(max_length=20)),
                ('day_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dayphong')),
                ('loai_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.loaiphong')),
            ],
        ),
        migrations.CreateModel(
            name='BaoHong',
            fields=[
                ('ma_bh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mo_ta', models.TextField()),
                ('ngay_bao', models.DateField()),
                ('trang_thai', models.CharField(max_length=20)),
                ('ma_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.phong')),
            ],
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('ma_hop_dong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_vao', models.DateField()),
                ('ngay_ra', models.DateField()),
                ('ma_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.phong')),
                ('mssv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('ma_hoa_don', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('so_tien', models.FloatField()),
                ('loai_hoa_don', models.CharField(max_length=20)),
                ('ngay_thanh_toan', models.DateField(blank=True, null=True)),
                ('thang', models.IntegerField()),
                ('ma_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.phong')),
                ('mssv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='DonDangKy',
            fields=[
                ('ma_don', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_dang_ky', models.DateField()),
                ('trang_thai', models.CharField(max_length=20)),
                ('loai_phong', models.CharField(max_length=20)),
                ('day_phong', models.CharField(max_length=20)),
                ('mssv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='tai_khoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dormitory.taikhoan'),
        ),
        migrations.CreateModel(
            name='QuanLy',
            fields=[
                ('ma_quan_ly', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_quan_ly', models.CharField(max_length=50)),
                ('cccd', models.CharField(max_length=12)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.BooleanField()),
                ('que_quan', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=15)),
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dormitory.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='ViPham',
            fields=[
                ('ma_vi_pham', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mo_ta', models.TextField()),
                ('muc_do', models.CharField(max_length=20)),
                ('hinh_thuc_xu_ly', models.CharField(max_length=50)),
                ('mssv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietTaiSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('ma_day_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dayphong')),
                ('ma_loai_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.loaiphong')),
                ('ma_tai_san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.taisan')),
            ],
            options={
                'unique_together': {('ma_day_phong', 'ma_loai_phong', 'ma_tai_san')},
            },
        ),
    ]
