# Generated by Django 5.2 on 2025-04-21 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiSoDienNuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('chi_so_dien_cu', models.IntegerField()),
                ('chi_so_dien_moi', models.IntegerField()),
                ('chi_so_nuoc_cu', models.IntegerField()),
                ('chi_so_nuoc_moi', models.IntegerField()),
                ('ngay_ghi', models.DateField()),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('hoa_don', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chi_so_dien_nuoc', to='dormitory.hoadon')),
                ('ma_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.phong')),
            ],
            options={
                'ordering': ['-nam', '-thang'],
                'unique_together': {('ma_phong', 'thang', 'nam')},
            },
        ),
    ]
